@baseUrl = http://localhost:8081

### Encrypt with AES-CBC-256
POST {{baseUrl}}/api/v1/encrypt
Content-Type: application/json

{
  "input": "Hello World",
  "algorithm": "AES_CBC_256"
}

### Decrypt with AES-CBC-256
POST {{baseUrl}}/api/v1/decrypt
Content-Type: application/json

{
  "input": "yS6XB8ZEdm340Bb8Tk/n6Q==",
  "algorithm": "AES_CBC_256"
}

### Encrypt with AES-GCM-256
POST {{baseUrl}}/api/v1/encrypt
Content-Type: application/json

{
  "input": "Hello World",
  "algorithm": "AES_GCM_256"
}

### Decrypt with AES-GCM-256
POST {{baseUrl}}/api/v1/decrypt
Content-Type: application/json

{
  "input": "gOv5EgSv3IcCfQPR9TFw7ib3NId59UnQAgPI",
  "algorithm": "AES_GCM_256"
}


### Encrypt with RSA-OAEP-2048
POST {{baseUrl}}/api/v1/encrypt
Content-Type: application/json

{
  "input": "Hello World",
  "algorithm": "RSA_OAEP"
}


### Decrypt with RSA-OAEP-2048
POST {{baseUrl}}/api/v1/decrypt
Content-Type: application/json

{
  "input": "tzwagf0B8u38czq/6kGsJflUEjiMNKGokzz2SzuHrD2lJIFEYazYFNdhu5eNbjZMMfQnCJP9mv6WceQOTQD+kPngdgG2KFqrlFcAM3SYwrXuW7LNjWwdWecrcbmXcCKgPE1bJThhNF7bqlRWvAdaXuwSB5/9ow272D6qZHt4Djm6zTjT3Nn87hYTENWQOo8OxM5tteLGpmRoFKAtYw94+rVhmsQdJM32rZO5yLaglS6vEkZ8nlyMpHP+HD5nMXzwMlhVlBdv7fywpfc1no9i2jXEI9KzPtA06ECSVrz8lrCYmh4ylyBe2kyaHXaEFgq5bUrsKG5OuRLmghO/tRu3Sg==",
  "algorithm": "RSA_OAEP"
}

### Encrypt with TRIPLE-DES-CBC
POST {{baseUrl}}/api/v1/encrypt
Content-Type: application/json

{
  "input": "Hello World",
  "algorithm": "TRIPLE_DES_CBC"
}
